# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  disk1 = "~/centos7-vagrant_default_1548708640723_14591/disk1.vdmk"
  disk2 = "~/centos7-vagrant_default_1548708640723_14591/disk2.vdmk"
  disk3 = "~/centos7-vagrant_default_1548708640723_14591/disk3.vdmk"
  disk4 = "~/centos7-vagrant_default_1548708640723_14591/disk4.vdmk"
  disk5 = "~/centos7-vagrant_default_1548708640723_14591/disk5.vdmk"
  config.vm.provider "virtualbox" do |vb|
  vb.memory = 1024
  vb.cpus = 1
  vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata"]
      unless File.exist?(disk1)
  	  vb.customize ['createhd', '--filename', disk1, '--size', 500]
  	  end
  	  unless File.exist?(disk2)
      vb.customize ['createhd', '--filename', disk2, '--size', 500]
      end
      unless File.exist?(disk3)
      vb.customize ['createhd', '--filename', disk3, '--size', 500]
      end
      unless File.exist?(disk4)
      vb.customize ['createhd', '--filename', disk4, '--size', 500]
      end
      unless File.exist?(disk5)
      vb.customize ['createhd', '--filename', disk5, '--size', 500]
      end
        vb.customize ['storageattach', :id, '--storagectl', 'SATA', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', disk1]
        vb.customize ['storageattach', :id, '--storagectl', 'SATA', '--port', 3, '--device', 0, '--type', 'hdd', '--medium', disk2]
        vb.customize ['storageattach', :id, '--storagectl', 'SATA', '--port', 4, '--device', 0, '--type', 'hdd', '--medium', disk3]
        vb.customize ['storageattach', :id, '--storagectl', 'SATA', '--port', 5, '--device', 0, '--type', 'hdd', '--medium', disk4]
        vb.customize ['storageattach', :id, '--storagectl', 'SATA', '--port', 6, '--device', 0, '--type', 'hdd', '--medium', disk5]

  end

  config.vm.provision "file", source: "/home/pool80/scripts/make-raid.sh", destination: "make-raid.sh"
  config.vm.provision "shell",
    inline:
     <<-SHELL
      yum install -y mdadm
      /bin/sh /home/vagrant/make-raid.sh
   SHELL

end
