Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.box_check_update = false
    config.vm.network "forwarded_port", guest: 80, host: 8080
  
  
    config.vm.provision "file", source: "/home/pool80/scripts/nginx.conf", destination: "nginx.conf"
    config.vm.provision "shell", inline: <<-SHELL
    yum update -y
    yum install epel-release -y
    yum install nginx -y
    cp ~vagrant/nginx.conf /etc/nginx/
    systemctl start nginx
    systemctl enable nginx
    SHELL
end