version: '3'
services:
  node1:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0.16
    ports:
      - "3301:3306"
    command: ["mysqld","--server_id=1","--binlog_checksum=NONE",
    "--gtid_mode=ON","--enforce_gtid_consistency=ON",
    "--log_bin","--log_slave_updates=ON",
    "--master_info_repository=TABLE","--relay_log_info_repository=TABLE",
    "--transaction_write_set_extraction=XXHASH64","--user=mysql",
    "--skip-host-cache","--skip-name-resolve",
     "--default_authentication_plugin=mysql_native_password"]
  node2:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0.16
    command: ["mysqld","--server_id=1","--binlog_checksum=NONE",
    "--gtid_mode=ON","--enforce_gtid_consistency=ON",
    "--log_bin","--log_slave_updates=ON",
    "--master_info_repository=TABLE","--relay_log_info_repository=TABLE",
    "--transaction_write_set_extraction=XXHASH64","--user=mysql",
    "--skip-host-cache","--skip-name-resolve",
     "--default_authentication_plugin=mysql_native_password"]
    ports:
      - "3302:3306"
  node3:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0.16
    command: ["mysqld","--server_id=1","--binlog_checksum=NONE",
    "--gtid_mode=ON","--enforce_gtid_consistency=ON",
    "--log_bin","--log_slave_updates=ON",
    "--master_info_repository=TABLE","--relay_log_info_repository=TABLE",
    "--transaction_write_set_extraction=XXHASH64","--user=mysql",
    "--skip-host-cache","--skip-name-resolve",
     "--default_authentication_plugin=mysql_native_password"]
    ports:
      - "3303:3306"
  mysql-shell:
    env_file:
      - mysql-shell.env
    image: pool80/mysql-shell-batch:0.4
    volumes:
        - ./scripts/:/scripts/
    depends_on:
      - node1
      - node2
      - node3
  mysql-router:
    env_file:
      - mysql-router.env
    image: mysql/mysql-router:8.0.16
    ports:
      - "6446:6446"
    depends_on:
      - node1
      - node2
      - node3
      - mysql-shell
    restart: on-failure
  
