Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.box_check_update = false
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.network "forwarded_port", guest: 8000, host: 8000
    config.vm.network "forwarded_port", guest: 3000, host: 3000
  
  
 #   config.vm.provision "file", source: "/home/pool80/otus/otus/lesson26_dynamic_web/conf", destination: "~"
    config.vm.provision "shell", inline: <<-SHELL
    setenforce 0
    systemctl start firewalld
    systemctl enable firewalld
    firewall-cmd --permanent --add-port=8000/tcp
    mkdir -p /var/www
    yum update -y
    yum install -y epel-release
    yum install -y vim yum-utils
    yum -y install nginx
    systemctl start nginx
    systemctl enable nginx
    rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
    yum install -y php72w php72w-curl php72w-common php72w-cli php72w-mysql \
    php72w-mbstring php72w-fpm php72w-xml php72w-pdo php72w-zip    
    
    #yum install -y https://centos7.iuscommunity.org/ius-release.rpm
    #yum install -y python36u python36u-devel python36u-pip
    #pip3.6 install --upgrade pip
    #pip3.6 install django-cms
    SHELL
end