# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:inetRouter => {
        :box_name => "centos/6",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                ]
  },
:centralRouter => {
        :box_name => "centos/7",
        :net => [
									 {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
									 {ip: '192.168.255.5', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
									 {ip: '192.168.255.9', adapter: 4, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
									 {ip: '192.168.0.1', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "dir-net"},
									 {ip: '192.168.0.33', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "hw-net"},
									 {ip: '192.168.0.65', adapter: 7, netmask: "255.255.255.192", virtualbox__intnet: "mgt-net"}
                ]
  },
  
:centralServer => {
        :box_name => "centos/7",
        :net => [
									 {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                ]
 },
	
:office1Router => {
          :box_name => "centos/7",
          :net => [
                   {ip: '192.168.255.6', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.2.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dev-net"},
                   {ip: '192.168.2.65', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "testserv-net"},
                   {ip: '192.168.2.129', adapter: 5, netmask: "255.255.255.240", virtualbox__intnet: "mng-net"},
                   {ip: '192.168.2.193', adapter: 6, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
                  ]
 },

:office1Server => {
          :box_name => "centos/7",
          :net => [
                   {ip: '192.168.2.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dev-net"},
					
                 ]
},

:office2Router => {
          :box_name => "centos/7",
          :net => [
                   {ip: '192.168.255.10', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.1.1', adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "dev-net"},
                   {ip: '192.168.1.128', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "testserv-net"},
                   {ip: '192.168.1.192', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "hw-net"},
                  ]
 },
	
:office2Server => {
          :box_name => "centos/7",
          :net => [
                   {ip: '192.168.1.2', adapter: 2, netmask: "255.255.255.128", virtualbox__intnet: "dev-net"},
											
                     ]
 },
	
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
		box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
		case boxname.to_s
		when "inetRouter"
			box.vm.provision "shell", inline: <<-SHELL
			echo -e 'net.ipv4.conf.all.forwarding=1\nnet.ipv4.ip_forward=1' >> /etc/sysctl.conf
			sysctl -p
			iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
			echo "192.168.0.0/16 via 192.168.255.2" >  /etc/sysconfig/network-scripts/route-eth1
			service network restart
			SHELL
		when "centralRouter"
			box.vm.provision "shell", inline: <<-SHELL
			echo -e 'net.ipv4.conf.all.forwarding=1\nnet.ipv4.ip_forward=1' >> /etc/sysctl.d/99-override.conf
			sysctl --system
			echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
			echo "DEVICE=eth1\nBOOTPROTO=static\nBROADCAST=192.168.255.3\nIPADDR=192.168.255.2\nNETMASK=255.255.255.252\nNETWORK=192.168.255.0\nONBOOT=yes\nGATEWAY=192.168.255.1\nDEFROUTE=yes" > /etc/sysconfig/network-scripts/ifcfg-eth1
			echo "DEVICE=eth2\nBOOTPROTO=static\nBROADCAST=192.168.255.7\nIPADDR=192.168.255.5\nNETMASK=255.255.255.252\nNETWORK=192.168.255.4\nONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-eth2
			echo "DEVICE=eth3\nBOOTPROTO=static\nBROADCAST=192.168.255.11\nIPADDR=192.168.255.9\nNETMASK=255.255.255.252\nNETWORK=192.168.255.8\nONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-eth3
			echo "DEVICE=eth4\nBOOTPROTO=static\nBROADCAST=192.168.0.15\nIPADDR=192.168.0.1\nNETMASK=255.255.255.240\nNETWORK=192.168.0.0\nONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-eth4
			echo "DEVICE=eth5\nBOOTPROTO=static\nBROADCAST=192.168.0.63\nIPADDR=192.168.0.33\nNETMASK=255.255.255.240\nNETWORK=192.168.0.32\nONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-eth5
			echo "DEVICE=eth6\nBOOTPROTO=static\nBROADCAST=192.168.0.127\nIPADDR=192.168.0.65\nNETMASK=255.255.255.192\nNETWORK=192.168.0.64\nONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-eth6
			echo "192.168.2.0/24 via 192.168.255.6" >  /etc/sysconfig/network-scripts/route-eth2
			echo "192.168.1.0/24 via 192.168.255.10" >> /etc/sysconfig/network-scripts/route-eth3
			systemctl restart network
			SHELL
		when "centralServer"
			box.vm.provision "shell", inline: <<-SHELL
			echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
			echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
			echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth2
			echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth3
			systemctl restart network
			SHELL
		when "office1Router"
			box.vm.provision "shell", inline: <<-SHELL
			echo -e 'net.ipv4.conf.all.forwarding=1\nnet.ipv4.ip_forward=1' >> /etc/sysctl.d/99-override.conf
			sysctl --system
			echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
			echo "DEVICE=eth1\nBOOTPROTO=static\nBROADCAST=192.168.255.7\nIPADDR=192.168.255.6\nNETMASK=255.255.255.252\nNETWORK=192.168.255.4\nGATEWAY=192.168.255.5\nONBOOT=yes\nDEFROUTE=yes" > /etc/sysconfig/network-scripts/ifcfg-eth
			systemctl restart network
			SHELL
		when "office1Server"
			box.vm.provision "shell", inline: <<-SHELL
			echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
			echo "DEVICE=eth1\nBOOTPROTO=static\nBROADCAST=192.168.2.255\nIPADDR=192.168.2.2\nNETMASK=255.255.255.0\nNETWORK=192.168.2.0\nGATEWAY=192.168.2.1\nONBOOT=yes\nDEFROUTE=yes" > /etc/sysconfig/network-scripts/ifcfg-eth1
			systemctl restart network
			SHELL
		when "office2Router"
			box.vm.provision "shell", inline: <<-SHELL
			echo -e 'net.ipv4.conf.all.forwarding=1\nnet.ipv4.ip_forward=1' >> /etc/sysctl.d/99-override.conf
			sysctl --system
			echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
			echo "DEVICE=eth1\nBOOTPROTO=static\nBROADCAST=192.168.255.11\nIPADDR=192.168.255.10\nNETMASK=255.255.255.252\nNETWORK=192.168.255.8\nGATEWAY=192.168.255.9\nONBOOT=yes\nDEFROUTE=yes" > /etc/sysconfig/network-scripts/ifcfg-eth1
			echo "GATEWAY=192.168.255.9" >> /etc/sysconfig/network-scripts/ifcfg-eth1
			systemctl restart network
			SHELL
		when "office2Server"
			box.vm.provision "shell", inline: <<-SHELL
			echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
			echo "DEVICE=eth1\nBOOTPROTO=static\nBROADCAST=192.168.1.255\nIPADDR=192.168.1.2\nNETMASK=255.255.255.0\nNETWORK=192.168.1.0\nGATEWAY=192.168.1.1\nONBOOT=yes\nDEFROUTE=yes" > /etc/sysconfig/network-scripts/ifcfg-eth1
			systemctl restart network
			SHELL
        end

      end

  end
  
  
end